#!/bin/sh

[ ! -f bin/rspec ] && {
  script/bootstrap
}

echo
echo "Spec"
echo "----"

specs=`find spec -name '*_spec.rb' -not -path 'spec/fixtures/*' -print | tr "\n" ' '`

bin/rspec ${specs} 2>/dev/null
